version: "3.9"
services:
  postgres:
    image: postgres:13.3
    environment:
      POSTGRES_DB: "Wallet-service"
      POSTGRES_USER: "dorogokupets"
      POSTGRES_PASSWORD: "ltl123"
    ports:
      - "5432:5432"